import { describe, it, expect } from "vitest";
import { evaluatePublicationQuality } from "../src/quality-gate.js";
import { EvidenceSignalItem, ClaimEvidenceLinkItem } from "@buildworth/shared";

describe("Synthetic Fixture & Legacy Isolation Defense in Quality Gate", () => {
  const syntheticSignal: EvidenceSignalItem = {
    id: "sig-synthetic-1",
    sourceId: "src-mock",
    sourceTitle: "Mock LLM Generator",
    sourceFamily: "SYNTHETIC",
    canonicalUrl: "https://synthetic.internal/quote/1",
    credibilityTier: null,
    evidenceOrigin: "SYNTHETIC_FIXTURE",
    verificationStatus: "VERIFIED",
    verificationMethod: "AUTOMATED_SOURCE_VALIDATION",
    sanitizedExcerpt: "Synthetic pain quote generated by test runner.",
    independenceKey: "synth:1",
    independenceConfidence: 1.0,
    collectedAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
    publishedAtPrecision: "EXACT_TIMESTAMP",
    purchaseIntent: true,
    spendingSignal: "$500/mo",
    desiredOutcome: "Automated testing",
    language: "en",
    signalType: "PURCHASE_INTENT",
    isContradiction: false,
  };

  const syntheticLink: ClaimEvidenceLinkItem = {
    id: "link-synth-1",
    opportunityRevisionId: "rev-1",
    claimType: "PAIN_EXISTENCE",
    claimIdentifier: "pain_existence",
    relationshipType: "SUPPORTS",
    supportStrength: "STRONG",
    explanation: "Synthetic support",
    relevanceScore: 0.95,
    signal: syntheticSignal,
  };

  it("fails if SYNTHETIC_FIXTURE passes the publication gate (must be HYPOTHESIS)", () => {
    const gate = evaluatePublicationQuality([syntheticLink], 80, false);

    expect(gate.status).toBe("HYPOTHESIS");
    expect(gate.metrics.hasSyntheticFixture).toBe(true);
    expect(gate.blockers.some((b) => b.includes("Contains SYNTHETIC_FIXTURE evidence"))).toBe(true);
  });

  it("fails if LEGACY_UNCLASSIFIED signals pass the publication gate (must be HYPOTHESIS)", () => {
    const legacySignal: EvidenceSignalItem = {
      ...syntheticSignal,
      id: "sig-legacy-1",
      evidenceOrigin: "LEGACY_UNCLASSIFIED",
      verificationStatus: "VERIFIED",
    };
    const legacyLink: ClaimEvidenceLinkItem = {
      ...syntheticLink,
      id: "link-legacy-1",
      signal: legacySignal,
    };

    const gate = evaluatePublicationQuality([legacyLink], 80, false);

    expect(gate.status).toBe("HYPOTHESIS");
    expect(gate.metrics.verifiedSignals).toBe(0);
  });
});
