export const APP_CONSTANTS = {
  DEFAULT_CURRENCY: "USD" as const,
  DEFAULT_SCORING_RUBRIC_VERSION: "1.0.0",
  MAX_EXCERPT_LENGTH: 280,
  HYPOTHESIS_CONFIDENCE_THRESHOLD: 50,
  HIGH_SCORE_THRESHOLD: 70,
  AI_DAILY_SPEND_LIMIT_CENTS_DEFAULT: 500, // $5.00
  AI_MONTHLY_SPEND_LIMIT_CENTS_DEFAULT: 15000, // $150.00
};
