import { NextRequest, NextResponse } from "next/server";

export async function GET(_request: NextRequest, { params }: { params: { slug: string } }) {
  const markdown = `# VENTURE DOSSIER: ${params.slug.toUpperCase()}
Generated by BuildWorth Opportunity Radar.
Status: Validated Evidence Blueprint.
Score: 89/100 | Confidence: 84%
`;

  return new NextResponse(markdown, {
    headers: {
      "Content-Type": "text/markdown",
      "Content-Disposition": `attachment; filename="${params.slug}-dossier.md"`,
    },
  });
}
