import { FullVentureBlueprint, DecisionRecommendation } from "@buildworth/shared";

const defaultSoc2FinancialMetrics = {
  monthlyRevenueCents: { status: "CALCULATED" as const, value: 199000 },
  monthlyVariableCostCents: { status: "CALCULATED" as const, value: 15000 },
  monthlyContributionMarginCents: { status: "CALCULATED" as const, value: 184000 },
  contributionMarginPerCustomerCents: { status: "CALCULATED" as const, value: 18400 },
  grossMarginPercent: { status: "CALCULATED" as const, value: 92.5 },
  monthlyOperatingProfitCents: { status: "CALCULATED" as const, value: 169000 },
  breakEvenCustomers: { status: "CALCULATED" as const, value: 2 },
  customerAnnualCostCents: { status: "CALCULATED" as const, value: 238800 },
  customerAnnualBenefitCents: { status: "CALCULATED" as const, value: 960000 },
  customerNetAnnualBenefitCents: { status: "CALCULATED" as const, value: 721200 },
  customerRoiPercent: { status: "CALCULATED" as const, value: 302.0 },
  customerPaybackMonths: { status: "CALCULATED" as const, value: 2.9 },
  providerCacPaybackMonths: { status: "CALCULATED" as const, value: 0.7 },
};

const defaultSnowflakeFinancialMetrics = {
  monthlyRevenueCents: { status: "CALCULATED" as const, value: 249000 },
  monthlyVariableCostCents: { status: "CALCULATED" as const, value: 25000 },
  monthlyContributionMarginCents: { status: "CALCULATED" as const, value: 224000 },
  contributionMarginPerCustomerCents: { status: "CALCULATED" as const, value: 22400 },
  grossMarginPercent: { status: "CALCULATED" as const, value: 90.0 },
  monthlyOperatingProfitCents: { status: "CALCULATED" as const, value: 199000 },
  breakEvenCustomers: { status: "CALCULATED" as const, value: 2 },
  customerAnnualCostCents: { status: "CALCULATED" as const, value: 298800 },
  customerAnnualBenefitCents: { status: "CALCULATED" as const, value: 4200000 },
  customerNetAnnualBenefitCents: { status: "CALCULATED" as const, value: 3901200 },
  customerRoiPercent: { status: "CALCULATED" as const, value: 1305.0 },
  customerPaybackMonths: { status: "CALCULATED" as const, value: 0.9 },
  providerCacPaybackMonths: { status: "CALCULATED" as const, value: 0.8 },
};

export const SOC2_BLUEPRINT_DEV_FIXTURE: FullVentureBlueprint = {
  id: "bp-soc2-canonical-v1",
  opportunityRevisionId: "rev-soc2-canonical-v1",
  schemaVersion: "1.0.0",
  generationStatus: "SYNTHESIZED",
  generatedAt: new Date().toISOString(),
  calculationVersion: "1.0.0",
  decisionRuleVersion: "1.0.0",
  inputHash: "a1b2c3d4e5f67890123456789abcdef0123456789abcdef0123456789abcdef0",

  architectureSummary: "Lightweight cloud event listener + Webhook relay + Next.js dashboard backed by PostgreSQL with zero-knowledge secret storage.",
  gtmNarrative: {
    initialWedge: "Automated PR approval signature capture and Vercel env snapshots.",
    leadSource: "Targeted outbound to DevOps engineers and Eng Directors.",
    outreachApproach: "Direct benchmark audit report showing 3 recurring invoice leak areas.",
    proofRequired: "Read-only IAM policy template with verifiable SOC2 evidence checklist.",
    initialOffer: "14-day free pilot with 100% money-back guarantee.",
    pilotStructure: "Self-service AWS CloudFormation stack launch + automated 24h baseline audit.",
    objectionPlaybook: [
      {
        objection: "We already have Vanta / Drata",
        responseHypothesis: "Vanta does broad GRC; we provide deep continuous git-level proof.",
      },
    ],
  },
  first20Plan: {
    stage1_5: {
      icp: "Series A B2B SaaS engineering managers with SOC2 requirements",
      channel: "Direct personal outreach to 50 active founders in YC / Techstars networks",
      offer: "White-glove concierge setup with 50% discount on annual plan",
      metric: "5 signed pilots within 21 days",
    },
    stage6_10: {
      referralMechanisms: "Introduce $500 referral reward",
      caseStudyProof: "Publish 2 detailed case studies documenting 40 hrs saved",
      pricingTest: "Introduce standard $199/mo self-service tier",
    },
    stage11_15: {
      repeatableChannel: "Targeted LinkedIn sponsored posts",
      salesMaterials: "Automated ROI calculator interactive tool",
      activationMetric: "< 10 minutes from signup to first webhook delivery",
    },
    stage16_20: {
      channelComparison: "Compare CAC between direct outreach and paid social",
      retentionCheck: "Verify 30-day active retention is > 85%",
      scaleDecision: "Commit to dedicated content marketing",
    },
  },
  reachableMarket: {
    method: "Bottom-up account penetration based on US & EU Series A-C venture-backed SaaS startups",
    inputValues: { totalStartups: 42000, awsShare: 0.65, serviceableShare: 0.15, avgAnnualPrice: 2388 },
    assumptions: ["65% of target companies use AWS as primary cloud", "15% actively seek 3rd party evidence collection"],
    lowerBoundCents: 450000000,
    baseCaseCents: 978000000,
    upperBoundCents: 1850000000,
    confidence: 75,
  },

  customerSegments: [
    {
      id: "seg-1",
      segmentName: "High-Growth Seed to Series B Startups",
      industry: "DevOps & Compliance",
      companySizeRange: "15 - 80 employees",
      geography: "North America & Remote",
      businessModel: "SaaS / Subscription",
      endUserRole: "Senior DevOps / SRE / Lead Software Engineer",
      economicBuyerRole: "VP of Engineering or Head of Security",
      technicalApproverRole: "Principal Security Architect",
      procurementComplexity: "Low (Credit card approval under $500/mo)",
      budgetCategory: "Engineering Tooling & Compliance",
      spendingBehavior: "Authorizes immediate departmental SaaS without RFP when ROI payback is < 60 days",
      buyingTrigger: "Upcoming annual SOC2 Type II audit deadline",
      primaryObjection: "Security clearance for third-party cloud infrastructure access",
      acquisitionChannels: ["Hacker News Launch", "Reddit r/devops discussions", "Targeted Founder Outbound"],
      salesCycleMinDays: 7,
      salesCycleMaxDays: 21,
      salesMotion: "FOUNDER_LED",
      confidenceScore: 85,
      provenanceType: "VERIFIED_EVIDENCE_BACKED",
      evidenceLinkIds: [],
    },
  ],

  mvpFeatures: [
    {
      id: "feat-1",
      featureName: "GitHub Action PR Signature Verification",
      description: "Automated commit signing & approval verification on merge.",
      category: "MUST_HAVE",
      requiredIntegrations: ["GitHub API"],
      requiredData: ["Commit SHA", "Author Email"],
      dependencies: [],
      acceptanceCriteria: ["Signature verified against GPG key"],
      orderIndex: 0,
    },
    {
      id: "feat-2",
      featureName: "Vercel Environment Snapshot Webhook",
      description: "Captures environment config changes automatically.",
      category: "MUST_HAVE",
      requiredIntegrations: ["Vercel Webhooks"],
      requiredData: ["Env Diff"],
      dependencies: [],
      acceptanceCriteria: ["Audit snapshot stored with HMAC"],
      orderIndex: 1,
    },
  ],

  competitors: [
    {
      id: "comp-1",
      name: "Vanta / Drata",
      competitorType: "Enterprise GRC",
      knownPricing: "$15k+/yr",
      strengths: ["Brand recognition", "Broad compliance framework support"],
      recurringComplaints: ["High cost", "Complex setup", "Lacks git-commit native binding"],
      differentiationHypothesis: "Developer-first git commit evidence capture at 1/10th cost",
      switchingCosts: "High once integrated into SOC2 audit workflow",
      provenanceType: "VERIFIED_EVIDENCE_BACKED",
      evidenceLinkIds: [],
    },
  ],

  costLineItems: [
    {
      id: "cost-1",
      costType: "ONE_TIME_BUILD",
      category: "BACKEND_DEV",
      title: "Initial MVP Action Development",
      scenarioType: "BASE",
      amountMinorCents: 500000,
      currency: "USD",
      estimateMethod: "100 engineering hours @ $50/hr",
      provenanceType: "VERIFIED_EVIDENCE_BACKED",
      evidenceLinkIds: [],
      assumptionIds: [],
      confidenceScore: 85,
    },
  ],

  benefitDrivers: [
    {
      id: "ben-1",
      category: "LABOR_TIME_SAVED",
      title: "Audit Preparation Elimination",
      affectedRole: "VP of Engineering",
      unitQuantity: 40,
      unitValueCents: 6000,
      frequencyPeriod: "ANNUAL",
      annualValueCents: 960000,
      calculationDescription: "40 hours saved per audit cycle at $60/hr.",
      provenanceType: "VERIFIED_EVIDENCE_BACKED",
      evidenceLinkIds: [],
      assumptionIds: [],
      confidenceScore: 85,
    },
  ],

  financialScenarios: [
    {
      ...defaultSoc2FinancialMetrics,
      scenarioType: "BASE",
      currency: "USD",
      activeCustomers: 10,
      monthlyPriceCents: 19900,
      onboardingPriceCents: 0,
      variableCostPerCustomerCents: 1500,
      monthlyFixedCostCents: 15000,
      customerAcquisitionCostCents: 12000,
      deliveryTimeWeeks: 4,
    },
  ],

  risks: [
    {
      id: "risk-1",
      category: "COMPETITION",
      description: "AWS introduces real-time hourly notifications in native Cost Explorer.",
      probabilityScore: 2,
      impactScore: 4,
      severity: "MEDIUM",
      mitigationStrategy: "Differentiate on cross-cloud support (GCP/Azure) and automated Slack remediation actions.",
      earlyWarningIndicator: "AWS re:Invent keynote product announcements.",
      status: "IDENTIFIED",
      evidenceLinkIds: [],
      provenanceType: "MODEL_ESTIMATE",
    },
  ],

  assumptions: [
    {
      id: "as-1",
      statement: "DevOps engineering leads have corporate credit card purchasing authority under $300/mo.",
      category: "WILLINGNESS_TO_PAY",
      importanceScore: 4,
      uncertaintyScore: 2,
      testMethod: "Targeted customer discovery interviews with 15 engineering leads.",
      successThreshold: "> 70% state yes without requiring VP approval",
      failureThreshold: "< 30% have credit card discretion",
      status: "SUPPORTED",
      evidenceLinkIds: [],
      provenanceType: "VERIFIED_EVIDENCE_BACKED",
    },
  ],

  validationExperiments: [
    {
      id: "exp-1",
      hypothesis: "Engineering managers will sign up for a free 14-day AWS Cost Anomaly pilot via targeted LinkedIn/HN outreach.",
      experimentType: "LANDING_PAGE",
      targetParticipant: "DevOps Engineers / VP Eng at Series A SaaS startups",
      sampleSize: 100,
      estimatedCostCents: 15000,
      estimatedDurationDays: 14,
      acquisitionChannel: "Hacker News ‘Show HN’ + Reddit r/devops targeted posts",
      procedureSummary: "Publish landing page with live interactive CloudFormation demo and waitlist opt-in.",
      successMetric: "Waitlist Conversion Rate",
      successThreshold: "> 8% conversion rate from unique visitors to verified work email waitlist",
      failureThreshold: "< 2% conversion rate",
      killCriterion: "< 1% conversion rate after 250 qualified visitors",
      nextActionOnSuccess: "Build narrow MVP single-tenant CloudFormation worker",
      nextActionOnFailure: "Pivot messaging toward compliance audit evidence instead of real-time spend",
      status: "PLANNED",
      orderPriority: 0,
      evidenceGeneratedIds: [],
    },
  ],

  decisionEvaluation: {
    recommendation: "BUILD_CANDIDATE" as DecisionRecommendation,
    reasonCodes: ["HIGH_SCORE_STRONG_EVIDENCE_HEALTHY_ECONOMICS", "ALL_COMMERCIAL_AND_EVIDENCE_GATES_PASSED"],
    blockingConditions: [],
    opportunityScoreUsed: 89,
    evidenceConfidenceUsed: 82,
    publicationStatusUsed: "VERIFIED",
    economicsStatus: "HEALTHY_HIGH_MARGIN",
    feasibilityStatus: "PROVEN_MODERN_STACK",
    criticalRiskIds: [],
    invalidatedAssumptionIds: [],
    decisionRuleVersion: "1.0.0",
    inputHash: "a1b2c3d4e5f67890123456789abcdef0123456789abcdef0123456789abcdef0",
    evaluatedAt: new Date().toISOString(),
  },
};

export const SNOWFLAKE_BLUEPRINT_DEV_FIXTURE: FullVentureBlueprint = {
  id: "bp-snowflake-canonical-v1",
  opportunityRevisionId: "rev-snowflake-canonical-v1",
  schemaVersion: "1.0.0",
  generationStatus: "SYNTHESIZED",
  generatedAt: new Date().toISOString(),
  calculationVersion: "1.0.0",
  decisionRuleVersion: "1.0.0",
  inputHash: "b2c3d4e5f67890123456789abcdef0123456789abcdef0123456789abcdef01",

  architectureSummary: "Real-time Snowflake query interceptor & credit usage circuit breaker with webhook alerting.",
  gtmNarrative: {
    initialWedge: "Automated Slack alerts when queries exceed 50 credits.",
    leadSource: "Targeted outbound to Data Leads & FinOps managers.",
    outreachApproach: "Direct query log audit report showing warehouse runaway anomalies.",
    proofRequired: "Read-only account usage query role template.",
    initialOffer: "14-day free pilot.",
    pilotStructure: "Self-service query monitoring script deployment.",
    objectionPlaybook: [
      {
        objection: "We use Snowflake native resource monitors",
        responseHypothesis: "Resource monitors are warehouse-level; we provide granular per-query auto-cancellation.",
      },
    ],
  },
  first20Plan: {
    stage1_5: {
      icp: "Data engineering leads with monthly Snowflake spend > $10,000",
      channel: "Direct outreach via LinkedIn & dbt Slack community",
      offer: "White-glove query audit with 50% pilot discount",
      metric: "5 signed pilots",
    },
    stage6_10: {
      referralMechanisms: "Data team peer referral credits",
      caseStudyProof: "Case study documenting $4k/mo saved in runaway query prevention",
      pricingTest: "Standard $249/mo tier",
    },
    stage11_15: {
      repeatableChannel: "dbt Slack & FinOps community partnerships",
      salesMaterials: "Query cost simulator interactive tool",
      activationMetric: "< 15 minutes to first query alert",
    },
    stage16_20: {
      channelComparison: "Direct vs community inbound CAC",
      retentionCheck: "90% 30-day retention",
      scaleDecision: "Expand to BigQuery and Databricks support",
    },
  },
  reachableMarket: {
    method: "Bottom-up Snowflake enterprise customer count",
    inputValues: { totalStartups: 12000, awsShare: 0.50, serviceableShare: 0.20, avgAnnualPrice: 2988 },
    assumptions: ["Snowflake data warehouse adoption", "High query concurrency workloads"],
    lowerBoundCents: 250000000,
    baseCaseCents: 600000000,
    upperBoundCents: 1200000000,
    confidence: 60,
  },

  customerSegments: [
    {
      id: "seg-snow-1",
      segmentName: "Mid-Market & Scaleup Data Teams",
      industry: "Data Engineering & FinOps",
      companySizeRange: "50 - 250 employees",
      geography: "North America & Remote",
      businessModel: "B2B SaaS / Data Platform",
      endUserRole: "Senior Data Engineer / Analytics Engineer",
      economicBuyerRole: "Head of Data",
      technicalApproverRole: "Lead Data Architect",
      procurementComplexity: "Moderate",
      budgetCategory: "Data Infrastructure & FinOps",
      spendingBehavior: "Requires signoff from VP of Data / Engineering",
      buyingTrigger: "Unexpected month-end Snowflake invoice blowout over budget",
      primaryObjection: "Access to query history logs",
      acquisitionChannels: ["dbt Slack", "Locally Optimistic Community", "Direct Outbound"],
      salesCycleMinDays: 14,
      salesCycleMaxDays: 30,
      salesMotion: "FOUNDER_LED",
      confidenceScore: 70,
      provenanceType: "MODEL_ESTIMATE",
      evidenceLinkIds: [],
    },
  ],

  mvpFeatures: [
    {
      id: "feat-snow-1",
      featureName: "Query Watchdog Python Daemon",
      description: "Lightweight background worker querying Snowflake ACCOUNT_USAGE views.",
      category: "MUST_HAVE",
      requiredIntegrations: ["Snowflake API"],
      requiredData: ["Query History Logs"],
      dependencies: [],
      acceptanceCriteria: ["Polls account usage views with < 60s latency"],
      orderIndex: 0,
    },
    {
      id: "feat-snow-2",
      featureName: "Slack Circuit Breaker Webhook",
      description: "Real-time Slack notification with 1-click query cancel button.",
      category: "MUST_HAVE",
      requiredIntegrations: ["Slack Incoming Webhook"],
      requiredData: ["Query Cost Estimate"],
      dependencies: [],
      acceptanceCriteria: ["Delivers Slack alert with cancel action button"],
      orderIndex: 1,
    },
  ],

  competitors: [
    {
      id: "comp-snow-1",
      name: "Native Snowflake Resource Monitors",
      competitorType: "Platform Native Tool",
      knownPricing: "Included in Snowflake",
      strengths: ["Zero setup", "Direct native integration"],
      recurringComplaints: ["Suspends entire warehouse rather than individual runaway queries", "Delayed alert triggers"],
      differentiationHypothesis: "Granular single-query auto-cancellation without disrupting concurrent team workloads",
      switchingCosts: "Low",
      provenanceType: "MODEL_ESTIMATE",
      evidenceLinkIds: [],
    },
  ],

  costLineItems: [
    {
      id: "cost-snow-1",
      costType: "ONE_TIME_BUILD",
      category: "BACKEND_DEV",
      title: "Query Interceptor Worker Implementation",
      scenarioType: "BASE",
      amountMinorCents: 400000,
      currency: "USD",
      estimateMethod: "80 engineering hours @ $50/hr",
      provenanceType: "MODEL_ESTIMATE",
      evidenceLinkIds: [],
      assumptionIds: [],
      confidenceScore: 70,
    },
  ],

  benefitDrivers: [
    {
      id: "ben-snow-1",
      category: "AVOIDED_LOSSES",
      title: "Runaway Join Query Cost Prevention",
      affectedRole: "Head of Data",
      unitQuantity: 1,
      unitValueCents: 350000,
      frequencyPeriod: "MONTHLY",
      annualValueCents: 4200000,
      calculationDescription: "Prevents at least 1 runaway join blowout per month ($3,500+).",
      provenanceType: "MODEL_ESTIMATE",
      evidenceLinkIds: [],
      assumptionIds: [],
      confidenceScore: 70,
    },
  ],

  financialScenarios: [
    {
      ...defaultSnowflakeFinancialMetrics,
      scenarioType: "BASE",
      currency: "USD",
      activeCustomers: 10,
      monthlyPriceCents: 24900,
      onboardingPriceCents: 0,
      variableCostPerCustomerCents: 2500,
      monthlyFixedCostCents: 25000,
      customerAcquisitionCostCents: 18000,
      deliveryTimeWeeks: 3,
    },
  ],

  risks: [
    {
      id: "risk-snow-1",
      category: "TECHNICAL",
      description: "Snowflake query latency in Account Usage views delays auto-cancellation window.",
      probabilityScore: 3,
      impactScore: 4,
      severity: "HIGH",
      mitigationStrategy: "Use real-time query execution monitoring API where supported.",
      earlyWarningIndicator: "Snowflake documentation updates.",
      status: "IDENTIFIED",
      evidenceLinkIds: [],
      provenanceType: "MODEL_ESTIMATE",
    },
  ],

  assumptions: [
    {
      id: "as-snow-1",
      statement: "Data teams will install a third-party watchdog script on Snowflake account.",
      category: "BUYER",
      importanceScore: 5,
      uncertaintyScore: 3,
      testMethod: "Offer open-source CLI runner to 20 data engineers.",
      successThreshold: "> 30% install and run initial audit",
      failureThreshold: "< 10% adoption",
      status: "UNTESTED",
      evidenceLinkIds: [],
      provenanceType: "MODEL_ESTIMATE",
    },
  ],

  validationExperiments: [
    {
      id: "exp-snow-1",
      hypothesis: "Data teams will sign up for a hosted query watchdog after running a free open-source cost audit.",
      experimentType: "PROTOTYPE_TEST",
      targetParticipant: "Data Engineers and FinOps leads",
      sampleSize: 50,
      estimatedCostCents: 10000,
      estimatedDurationDays: 14,
      acquisitionChannel: "GitHub repository launch + Reddit r/dataengineering",
      procedureSummary: "Release CLI script on GitHub with link to hosted dashboard waitlist.",
      successMetric: "Waitlist conversion",
      successThreshold: "> 10% conversion from script runs to waitlist signup",
      failureThreshold: "< 2% conversion",
      killCriterion: "< 1% conversion after 100 CLI runs",
      nextActionOnSuccess: "Build narrow MVP hosted auto-canceler",
      nextActionOnFailure: "Pivot to BigQuery or AWS Athena cost alerting",
      status: "PLANNED",
      orderPriority: 0,
      evidenceGeneratedIds: [],
    },
  ],

  decisionEvaluation: {
    recommendation: "VALIDATE_FIRST" as DecisionRecommendation,
    reasonCodes: ["HYPOTHESIS_UNVERIFIED_EVIDENCE_REQUIRES_VALIDATION", "EVIDENCE_CONFIDENCE_BELOW_BUILD_THRESHOLD"],
    blockingConditions: ["EVIDENCE_NOT_VERIFIED", "HYPOTHESIS_STAGE"],
    opportunityScoreUsed: 80,
    evidenceConfidenceUsed: 0,
    publicationStatusUsed: "HYPOTHESIS",
    economicsStatus: "HEALTHY_HIGH_MARGIN",
    feasibilityStatus: "PROVEN_MODERN_STACK",
    criticalRiskIds: [],
    invalidatedAssumptionIds: [],
    decisionRuleVersion: "1.0.0",
    inputHash: "b2c3d4e5f67890123456789abcdef0123456789abcdef0123456789abcdef01",
    evaluatedAt: new Date().toISOString(),
  },
};

export const MOCK_BLUEPRINT_DEV_FIXTURE = SOC2_BLUEPRINT_DEV_FIXTURE;
