import { FullVentureBlueprint, DecisionRecommendation } from "@buildworth/shared";

/**
 * Isolated Development / Test Fixtures for Phase 2 Decision-Grade Blueprints.
 * These fixtures are strictly for development previews and local test suites.
 */
export const MOCK_BLUEPRINT_DEV_FIXTURE: FullVentureBlueprint = {
  id: "bp-dev-demo-1",
  opportunityRevisionId: "rev-dev-demo-1",
  schemaVersion: "1.0.0",
  generationStatus: "SYNTHESIZED",
  generatedAt: new Date().toISOString(),
  calculationVersion: "1.0.0",
  decisionRuleVersion: "1.0.0",
  inputHash: "a1b2c3d4e5f67890123456789abcdef0123456789abcdef0123456789abcdef0",

  architectureSummary: "Lightweight cloud event listener + Webhook relay + Next.js dashboard backed by PostgreSQL with zero-knowledge secret storage.",
  gtmNarrative: {
    initialWedge: "Automated Slack & PagerDuty alerts for sudden unexpected AWS RDS / EKS cost spikes without full enterprise agent installation.",
    leadSource: "Targeted outbound to DevOps engineers and Eng Directors participating in AWS outage / invoice spike discussions on Reddit & HN.",
    outreachApproach: "Direct benchmark audit report showing 3 recurring invoice leak areas in < 5 minutes.",
    proofRequired: "Read-only IAM policy template with verifiable SOC2 evidence checklist.",
    initialOffer: "14-day free pilot with 100% money-back guarantee on month 1 if no waste is identified.",
    pilotStructure: "Self-service AWS CloudFormation stack launch + automated 24h baseline audit.",
    objectionPlaybook: [
      {
        objection: "We already have Datadog / native AWS Cost Explorer",
        responseHypothesis: "Cost Explorer is 24h delayed; Datadog costs $15+/host. We give real-time instant alerts for a flat $199/mo.",
      },
      {
        objection: "Security policy prohibits read access to billing",
        responseHypothesis: "We provide scoped IAM roles limited strictly to Cost Explorer API with zero data plane access.",
      },
    ],
  },
  first20Plan: {
    stage1_5: {
      icp: "Series A B2B SaaS engineering managers with AWS monthly bills > $5,000",
      channel: "Direct personal outreach to 50 active founders in YC / Techstars networks",
      offer: "White-glove concierge setup with 50% discount on annual plan in exchange for video testimonial",
      metric: "5 signed pilots within 21 days",
    },
    stage6_10: {
      referralMechanisms: "Introduce $500 cloud credit referral reward for peer engineering leads",
      caseStudyProof: "Publish 2 detailed case studies documenting >$1,200/mo in saved idle resources",
      pricingTest: "Introduce standard $199/mo self-service credit card tier",
    },
    stage11_15: {
      repeatableChannel: "Targeted LinkedIn sponsored posts highlighting real-time cost anomaly alerts",
      salesMaterials: "Automated ROI calculator interactive tool and benchmark comparison sheet",
      activationMetric: "< 10 minutes from signup to first webhook alert delivery",
    },
    stage16_20: {
      channelComparison: "Compare CAC between direct founder outreach ($120) and paid social ($450)",
      retentionCheck: "Verify 30-day active retention is > 85% across initial cohort",
      scaleDecision: "Commit to dedicated content marketing and SEO directory ingestion",
    },
  },
  reachableMarket: {
    method: "Bottom-up account penetration based on US & EU Series A-C venture-backed SaaS startups using AWS",
    inputValues: { totalStartups: 42000, awsShare: 0.65, serviceableShare: 0.15, avgAnnualPrice: 2388 },
    assumptions: ["65% of target companies use AWS as primary cloud", "15% actively seek 3rd party cost alerting"],
    lowerBoundCents: 450000000, // $4.5M SOM
    baseCaseCents: 978000000, // $9.78M SOM
    upperBoundCents: 1850000000, // $18.5M SOM
    confidence: 75,
  },

  customerSegments: [
    {
      id: "seg-1",
      segmentName: "High-Growth Seed to Series B Startups",
      industry: "B2B Software & AI Services",
      companySizeRange: "15 - 80 employees",
      geography: "North America & Remote",
      businessModel: "SaaS / Subscription",
      endUserRole: "Senior DevOps / SRE / Lead Software Engineer",
      economicBuyerRole: "VP of Engineering or Head of Infrastructure",
      technicalApproverRole: "Principal Security Architect",
      procurementComplexity: "Low (Credit card approval under $500/mo)",
      budgetCategory: "Engineering Tooling & Cloud Infrastructure",
      spendingBehavior: "Authorizes immediate departmental SaaS without RFP when ROI payback is < 60 days",
      buyingTrigger: "Sudden unexpected month-end cloud invoice spike or pre-audit budget review",
      primaryObjection: "Security clearance for third-party cloud infrastructure access",
      acquisitionChannels: ["Hacker News Launch", "Reddit r/devops discussions", "Targeted Founder Outbound"],
      salesCycleMinDays: 7,
      salesCycleMaxDays: 21,
      salesMotion: "FOUNDER_LED",
      confidenceScore: 85,
      provenanceType: "VERIFIED_EVIDENCE_BACKED",
      evidenceLinkIds: [],
    },
  ],

  mvpFeatures: [
    {
      id: "feat-1",
      featureName: "One-Click IAM Role Deployment",
      description: "CloudFormation template granting strictly read-only cost metrics access in under 2 minutes.",
      category: "MUST_HAVE",
      userJourneyStep: "Onboarding",
      requiredIntegrations: ["AWS CloudFormation", "AWS STS"],
      requiredData: ["Cost and Usage Reports (CUR)"],
      dependencies: [],
      acceptanceCriteria: ["Deploys in < 120 seconds", "Zero permission errors on standard AWS accounts"],
      orderIndex: 0,
    },
    {
      id: "feat-2",
      featureName: "Real-Time Anomaly Alert Engine",
      description: "Hourly cron evaluating run-rate against 7-day rolling median with threshold trigger.",
      category: "MUST_HAVE",
      userJourneyStep: "Active Monitoring",
      requiredIntegrations: ["Slack Webhooks", "PagerDuty API", "Email (Resend)"],
      requiredData: ["Hourly cost telemetry"],
      dependencies: ["feat-1"],
      acceptanceCriteria: ["Alert delivers within 15 minutes of anomaly", "Zero false positives on scheduled batch jobs"],
      orderIndex: 1,
    },
    {
      id: "feat-3",
      featureName: "Root-Cause Resource Drilldown",
      description: "Identifies the exact resource ID, region, and tag responsible for the spike.",
      category: "MUST_HAVE",
      userJourneyStep: "Incident Investigation",
      requiredIntegrations: ["AWS CloudWatch"],
      requiredData: ["Resource ARN telemetry"],
      dependencies: ["feat-2"],
      acceptanceCriteria: ["Shows exact ARN and resource tag breakdown"],
      orderIndex: 2,
    },
    {
      id: "feat-4",
      featureName: "Multi-Cloud GCP & Azure Sync",
      description: "Extends cost monitoring across GCP projects and Azure subscriptions.",
      category: "LATER",
      userJourneyStep: "Scale Management",
      requiredIntegrations: ["GCP Cloud Billing API", "Azure Cost Management API"],
      requiredData: ["Cross-cloud billing logs"],
      dependencies: ["feat-2"],
      acceptanceCriteria: ["Unified multi-cloud dashboard view"],
      orderIndex: 3,
    },
  ],

  competitors: [
    {
      id: "comp-1",
      name: "Legacy Enterprise Suites (Datadog, Cloudability)",
      competitorType: "DIRECT",
      knownPricing: "$15k - $50k / year annual enterprise contracts",
      strengths: ["Broad multi-cloud telemetry", "Brand recognition in Fortune 500"],
      recurringComplaints: ["High opaque pricing", "Takes weeks of engineering setup", "Complex bloated dashboards"],
      differentiationHypothesis: "10x cheaper ($199/mo), zero sales calls, 2-minute setup with instant Slack alerts.",
      switchingCosts: "HIGH",
      provenanceType: "VERIFIED_EVIDENCE_BACKED",
      evidenceLinkIds: [],
    },
    {
      id: "comp-2",
      name: "Native Cloud Explorer (AWS Cost Explorer)",
      competitorType: "INDIRECT",
      knownPricing: "Free / Included in AWS account",
      strengths: ["Native integration", "Zero additional vendor review"],
      recurringComplaints: ["24-48 hour alert latency", "Clunky UI", "Does not notify on sudden run-rate spikes in real-time"],
      differentiationHypothesis: "Real-time alerting before invoice is locked at month end.",
      switchingCosts: "LOW",
      provenanceType: "VERIFIED_EVIDENCE_BACKED",
      evidenceLinkIds: [],
    },
  ],

  financialScenarios: [
    {
      scenarioType: "CONSERVATIVE",
      currency: "USD",
      activeCustomers: 15,
      monthlyPriceCents: 14900, // $149/mo
      onboardingPriceCents: 0,
      variableCostPerCustomerCents: 1800,
      monthlyFixedCostCents: 120000,
      customerAcquisitionCostCents: 35000,
      deliveryTimeWeeks: 6,
      grossMarginPercent: { status: "CALCULATED", value: 87.92 },
      monthlyRevenueCents: { status: "CALCULATED", value: 223500 },
      monthlyVariableCostCents: { status: "CALCULATED", value: 27000 },
      monthlyContributionMarginCents: { status: "CALCULATED", value: 196500 },
      contributionMarginPerCustomerCents: { status: "CALCULATED", value: 13100 },
      monthlyOperatingProfitCents: { status: "CALCULATED", value: 76500 },
      breakEvenCustomers: { status: "CALCULATED", value: 10 },
      customerAnnualCostCents: { status: "CALCULATED", value: 178800 },
      customerAnnualBenefitCents: { status: "CALCULATED", value: 1440000 },
      customerNetAnnualBenefitCents: { status: "CALCULATED", value: 1261200 },
      customerRoiPercent: { status: "CALCULATED", value: 705.37 },
      customerPaybackMonths: { status: "CALCULATED", value: 1.5 },
      providerCacPaybackMonths: { status: "CALCULATED", value: 2.7 },
    },
    {
      scenarioType: "BASE",
      currency: "USD",
      activeCustomers: 45,
      monthlyPriceCents: 19900, // $199/mo
      onboardingPriceCents: 0,
      variableCostPerCustomerCents: 1500,
      monthlyFixedCostCents: 180000,
      customerAcquisitionCostCents: 42000,
      deliveryTimeWeeks: 4,
      grossMarginPercent: { status: "CALCULATED", value: 92.46 },
      monthlyRevenueCents: { status: "CALCULATED", value: 895500 },
      monthlyVariableCostCents: { status: "CALCULATED", value: 67500 },
      monthlyContributionMarginCents: { status: "CALCULATED", value: 828000 },
      contributionMarginPerCustomerCents: { status: "CALCULATED", value: 18400 },
      monthlyOperatingProfitCents: { status: "CALCULATED", value: 648000 },
      breakEvenCustomers: { status: "CALCULATED", value: 10 },
      customerAnnualCostCents: { status: "CALCULATED", value: 238800 },
      customerAnnualBenefitCents: { status: "CALCULATED", value: 2160000 },
      customerNetAnnualBenefitCents: { status: "CALCULATED", value: 1921200 },
      customerRoiPercent: { status: "CALCULATED", value: 804.52 },
      customerPaybackMonths: { status: "CALCULATED", value: 1.3 },
      providerCacPaybackMonths: { status: "CALCULATED", value: 2.3 },
    },
    {
      scenarioType: "UPSIDE",
      currency: "USD",
      activeCustomers: 120,
      monthlyPriceCents: 29900, // $299/mo
      onboardingPriceCents: 0,
      variableCostPerCustomerCents: 1200,
      monthlyFixedCostCents: 350000,
      customerAcquisitionCostCents: 55000,
      deliveryTimeWeeks: 4,
      grossMarginPercent: { status: "CALCULATED", value: 95.99 },
      monthlyRevenueCents: { status: "CALCULATED", value: 3588000 },
      monthlyVariableCostCents: { status: "CALCULATED", value: 144000 },
      monthlyContributionMarginCents: { status: "CALCULATED", value: 3444000 },
      contributionMarginPerCustomerCents: { status: "CALCULATED", value: 28700 },
      monthlyOperatingProfitCents: { status: "CALCULATED", value: 3094000 },
      breakEvenCustomers: { status: "CALCULATED", value: 13 },
      customerAnnualCostCents: { status: "CALCULATED", value: 358800 },
      customerAnnualBenefitCents: { status: "CALCULATED", value: 3600000 },
      customerNetAnnualBenefitCents: { status: "CALCULATED", value: 3241200 },
      customerRoiPercent: { status: "CALCULATED", value: 903.34 },
      customerPaybackMonths: { status: "CALCULATED", value: 1.2 },
      providerCacPaybackMonths: { status: "CALCULATED", value: 1.9 },
    },
  ],

  costLineItems: [
    {
      id: "cost-1",
      costType: "ONE_TIME_BUILD",
      category: "UX_UI_DESIGN",
      title: "Interactive Dashboard & Alerts Flow",
      description: "Figma wireframes, component library, and notification layout design.",
      scenarioType: "BASE",
      amountMinorCents: 150000, // $1,500
      currency: "USD",
      estimateMethod: "20 hours @ $75/hr design rate",
      provenanceType: "MODEL_ESTIMATE",
      evidenceLinkIds: [],
      assumptionIds: [],
      confidenceScore: 80,
    },
    {
      id: "cost-2",
      costType: "ONE_TIME_BUILD",
      category: "BACKEND_DEV",
      title: "AWS Cost Ingestion & Anomaly Detector",
      description: "PostgreSQL schema, background worker cron, and Slack webhook dispatcher.",
      scenarioType: "BASE",
      amountMinorCents: 350000, // $3,500
      currency: "USD",
      estimateMethod: "35 hours @ $100/hr senior engineering rate",
      provenanceType: "MODEL_ESTIMATE",
      evidenceLinkIds: [],
      assumptionIds: [],
      confidenceScore: 85,
    },
    {
      id: "cost-3",
      costType: "MONTHLY_OPERATING",
      category: "HOSTING",
      title: "Managed PostgreSQL & Serverless Compute",
      description: "Vercel Pro + Neon PostgreSQL dedicated compute.",
      scenarioType: "BASE",
      amountMinorCents: 6000, // $60/mo
      currency: "USD",
      estimateMethod: "Provider Tier Rate Sheet",
      provenanceType: "VERIFIED_EVIDENCE_BACKED",
      evidenceLinkIds: [],
      assumptionIds: [],
      confidenceScore: 95,
    },
  ],

  benefitDrivers: [
    {
      id: "ben-1",
      category: "AVOIDED_LOSSES",
      title: "Prevention of Unplanned Resource Runaway Spikes",
      affectedRole: "Engineering Lead / VP of Eng",
      unitQuantity: 1,
      unitValueCents: 180000, // $1,800 saved per incident
      frequencyPeriod: "MONTHLY",
      annualValueCents: 2160000, // $21,600/year
      calculationDescription: "1 runaway compute/NAT gateway incident caught within hours instead of 30 days.",
      provenanceType: "VERIFIED_EVIDENCE_BACKED",
      evidenceLinkIds: [],
      assumptionIds: [],
      confidenceScore: 85,
    },
  ],

  risks: [
    {
      id: "risk-1",
      category: "COMPETITION",
      description: "AWS introduces real-time hourly notifications in native Cost Explorer.",
      probabilityScore: 2,
      impactScore: 4,
      severity: "MEDIUM",
      mitigationStrategy: "Differentiate on cross-cloud support (GCP/Azure) and automated Slack remediation actions.",
      earlyWarningIndicator: "AWS re:Invent keynote product announcements.",
      status: "IDENTIFIED",
      evidenceLinkIds: [],
      provenanceType: "MODEL_ESTIMATE",
    },
  ],

  assumptions: [
    {
      id: "as-1",
      statement: "DevOps engineering leads have corporate credit card purchasing authority under $300/mo.",
      category: "WILLINGNESS_TO_PAY",
      importanceScore: 4,
      uncertaintyScore: 2,
      testMethod: "Targeted customer discovery interviews with 15 engineering leads.",
      successThreshold: "> 70% state yes without requiring VP approval",
      failureThreshold: "< 30% have credit card discretion",
      status: "SUPPORTED",
      evidenceLinkIds: [],
      provenanceType: "VERIFIED_EVIDENCE_BACKED",
    },
  ],

  validationExperiments: [
    {
      id: "exp-1",
      hypothesis: "Engineering managers will sign up for a free 14-day AWS Cost Anomaly pilot via targeted LinkedIn/HN outreach.",
      experimentType: "LANDING_PAGE",
      targetParticipant: "DevOps Engineers / VP Eng at Series A SaaS startups",
      sampleSize: 100,
      estimatedCostCents: 15000, // $150 ad spend
      estimatedDurationDays: 14,
      acquisitionChannel: "Hacker News ‘Show HN’ + Reddit r/devops targeted posts",
      procedureSummary: "Publish landing page with live interactive CloudFormation demo and waitlist opt-in.",
      successMetric: "Waitlist Conversion Rate",
      successThreshold: "> 8% conversion rate from unique visitors to verified work email waitlist",
      failureThreshold: "< 2% conversion rate",
      killCriterion: "< 1% conversion rate after 250 qualified visitors",
      nextActionOnSuccess: "Build narrow MVP single-tenant CloudFormation worker",
      nextActionOnFailure: "Pivot messaging toward compliance audit evidence instead of real-time spend",
      status: "PLANNED",
      orderPriority: 0,
      evidenceGeneratedIds: [],
    },
  ],

  decisionEvaluation: {
    recommendation: "BUILD_CANDIDATE" as DecisionRecommendation,
    reasonCodes: ["HIGH_SCORE_STRONG_EVIDENCE_HEALTHY_ECONOMICS", "ALL_COMMERCIAL_AND_EVIDENCE_GATES_PASSED"],
    blockingConditions: [],
    opportunityScoreUsed: 88,
    evidenceConfidenceUsed: 84,
    publicationStatusUsed: "VERIFIED",
    economicsStatus: "HEALTHY_HIGH_MARGIN",
    feasibilityStatus: "PROVEN_MODERN_STACK",
    criticalRiskIds: [],
    invalidatedAssumptionIds: [],
    decisionRuleVersion: "1.0.0",
    inputHash: "a1b2c3d4e5f67890123456789abcdef0123456789abcdef0123456789abcdef0",
    evaluatedAt: new Date().toISOString(),
  },
};
