import { ClaimEvidenceLinkItem } from "@buildworth/shared";

export const VERIFIED_FIXTURE_EVIDENCE: ClaimEvidenceLinkItem[] = [
  {
    id: "link-v1",
    opportunityRevisionId: "rev-dev-1",
    normalizedSignalId: "sig-v1",
    claimType: "PAIN_EXISTENCE",
    claimIdentifier: "pain_existence",
    claimSnippet:
      "Our DevOps team burns 40+ engineering hours every single quarter taking manual screenshots for SOC2 auditor spreadsheets.",
    relationshipType: "SUPPORTS",
    supportStrength: "STRONG",
    relevanceScore: 0.96,
    explanation:
      "Direct firsthand report of recurring compliance screenshot capture burden from Senior Platform Engineer.",
    signal: {
      id: "sig-v1",
      sourceName: "Hacker News",
      sourceType: "HACKERNEWS_API",
      sourceFamily: "FORUM",
      credibilityTier: "TIER_2_CREDIBLE_PUBLIC",
      signalType: "PAIN",
      evidenceOrigin: "COLLECTED",
      canonicalUrl: "https://news.ycombinator.com/item?id=38491021",
      originalUrl: "https://news.ycombinator.com/item?id=38491021",
      sourceTitle: "Ask HN: How does your engineering team survive quarterly SOC2 audits?",
      authorOrg: "Series B Platform Lead",
      publishedAt: new Date(Date.now() - 14 * 24 * 3600 * 1000).toISOString(),
      publishedAtPrecision: "EXACT_TIMESTAMP",
      collectedAt: new Date().toISOString(),
      language: "en",
      sanitizedExcerpt:
        "Every quarter before the SOC2 Type II audit, we have to halt sprint work for 3 days just taking screenshots of GitHub PR approvals and AWS IAM settings. It is completely soul-crushing and error prone.",
      problemSummary: "Quarterly manual screenshot collection for audit evidence",
      actorRole: "Senior Platform Engineer",
      workflowContext: "Pre-audit compliance review sprints",
      purchaseIntent: false,
      evidenceQuality: 0.95,
      recencyScore: 1.0,
      credibilityScore: 0.85,
      independenceKey: "hn:story:38491021",
      independenceMethod: "ROOT_THREAD",
      independenceConfidence: 1.0,
      verificationStatus: "VERIFIED",
      verificationMethod: "TRUSTED_API",
      verifiedAt: new Date(Date.now() - 13 * 24 * 3600 * 1000).toISOString(),
      verifiedBy: "Automated Source Policy Engine v2.0",
      verificationNotes: "Passed DNS & SSL verification. Authentic Algolia item response.",
      lastAccessibilityCheckAt: new Date().toISOString(),
    },
  },
  {
    id: "link-v2",
    opportunityRevisionId: "rev-dev-1",
    normalizedSignalId: "sig-v2",
    claimType: "BUYER_IDENTITY",
    claimIdentifier: "buyer_identity",
    claimSnippet:
      "Official job postings for DevOps Engineers and Security Leads mandate SOC2 evidence pipeline management.",
    relationshipType: "SUPPORTS",
    supportStrength: "STRONG",
    relevanceScore: 0.94,
    explanation:
      "Primary employer requisition identifying Head of Security / VP Engineering as budget owners.",
    signal: {
      id: "sig-v2",
      sourceName: "GitHub Careers & RFCs",
      sourceType: "GITHUB_REST",
      sourceFamily: "CODE_HOST",
      credibilityTier: "TIER_1_PRIMARY",
      signalType: "JOB_POSTING",
      evidenceOrigin: "COLLECTED",
      canonicalUrl: "https://github.com/orgs/security-first/discussions/412",
      originalUrl: "https://github.com/orgs/security-first/discussions/412",
      sourceTitle: "RFC: Automated Git PR Attestation for SOC2 CC6.8",
      authorOrg: "VP of Engineering, FinTech Corp",
      publishedAt: new Date(Date.now() - 25 * 24 * 3600 * 1000).toISOString(),
      publishedAtPrecision: "EXACT_TIMESTAMP",
      collectedAt: new Date().toISOString(),
      language: "en",
      sanitizedExcerpt:
        "We are actively recruiting a Security Platform Lead. Must be able to implement automated cryptographic git commit attestations so engineers no longer waste time during our annual audit.",
      problemSummary: "Mandatory requirement for automated PR attestation",
      actorRole: "VP of Engineering",
      workflowContext: "Compliance governance & hiring mandate",
      purchaseIntent: true,
      spendingSignal: "$180k hiring requisition or SaaS budget",
      evidenceQuality: 0.98,
      recencyScore: 0.95,
      credibilityScore: 1.0,
      independenceKey: "github:repo:security-first/governance",
      independenceMethod: "REPOSITORY_LEVEL",
      independenceConfidence: 1.0,
      verificationStatus: "VERIFIED",
      verificationMethod: "TRUSTED_API",
      verifiedAt: new Date(Date.now() - 24 * 24 * 3600 * 1000).toISOString(),
      verifiedBy: "GitHub Verified API Connector",
      verificationNotes: "Authentic repository discussion thread from authenticated org member.",
      lastAccessibilityCheckAt: new Date().toISOString(),
    },
  },
  {
    id: "link-v3",
    opportunityRevisionId: "rev-dev-1",
    normalizedSignalId: "sig-v3",
    claimType: "BUYER_DEMAND",
    claimIdentifier: "buyer_demand",
    claimSnippet:
      "Founders seeking lightweight git-bound SOC2 collector to replace bloated $15k enterprise platforms.",
    relationshipType: "SUPPORTS",
    supportStrength: "STRONG",
    relevanceScore: 0.92,
    explanation: "Explicit search for lightweight focused point solution on community forum.",
    signal: {
      id: "sig-v3",
      sourceName: "Reddit r/devops",
      sourceType: "REDDIT_OAUTH",
      sourceFamily: "COMMUNITY",
      credibilityTier: "TIER_2_CREDIBLE_PUBLIC",
      signalType: "BUYER_DEMAND" as any,
      evidenceOrigin: "COLLECTED",
      canonicalUrl:
        "https://www.reddit.com/r/devops/comments/18x9k2/looking_for_lightweight_git_soc2_collector/",
      originalUrl:
        "https://www.reddit.com/r/devops/comments/18x9k2/looking_for_lightweight_git_soc2_collector/",
      sourceTitle: "Looking for lightweight Git SOC2 evidence collector (not Vanta)",
      authorOrg: "u/devops_lead_sf",
      publishedAt: new Date(Date.now() - 40 * 24 * 3600 * 1000).toISOString(),
      publishedAtPrecision: "DAY",
      collectedAt: new Date().toISOString(),
      language: "en",
      sanitizedExcerpt:
        "Is there any modern tool that simply watches GitHub Actions and Vercel deployments and stamps cryptographic audit proof? We do not need a massive $20k GRC suite, just git evidence automation.",
      problemSummary: "Active search for lightweight Git SOC2 evidence collector",
      actorRole: "DevOps Lead",
      workflowContext: "Tool evaluation",
      purchaseIntent: true,
      spendingSignal: "Looking to purchase point solution",
      evidenceQuality: 0.9,
      recencyScore: 0.9,
      credibilityScore: 0.8,
      independenceKey: "reddit:post:devops:18x9k2",
      independenceMethod: "SUBMISSION_THREAD",
      independenceConfidence: 1.0,
      verificationStatus: "VERIFIED",
      verificationMethod: "TRUSTED_API",
      verifiedAt: new Date(Date.now() - 39 * 24 * 3600 * 1000).toISOString(),
      verifiedBy: "Reddit API Validator",
      verificationNotes: "Authentic post from established Reddit account with >5k karma.",
      lastAccessibilityCheckAt: new Date().toISOString(),
    },
  },
  {
    id: "link-v4",
    opportunityRevisionId: "rev-dev-1",
    normalizedSignalId: "sig-v4",
    claimType: "WILLINGNESS_TO_PAY",
    claimIdentifier: "willingness_to_pay",
    claimSnippet:
      "Engineering leaders willing to pay $199-$499/mo on company credit card for automated compliance PR bot.",
    relationshipType: "SUPPORTS",
    supportStrength: "STRONG",
    relevanceScore: 0.95,
    explanation: "Stated willingness to pay on public engineering forum.",
    signal: {
      id: "sig-v4",
      sourceName: "Hacker News",
      sourceType: "HACKERNEWS_API",
      sourceFamily: "FORUM",
      credibilityTier: "TIER_2_CREDIBLE_PUBLIC",
      signalType: "WILLINGNESS_TO_PAY",
      evidenceOrigin: "COLLECTED",
      canonicalUrl: "https://news.ycombinator.com/item?id=38501199",
      originalUrl: "https://news.ycombinator.com/item?id=38501199",
      sourceTitle: "Show HN: Automated Git Evidence Collector",
      authorOrg: "CTO, YC W23 Batch",
      publishedAt: new Date(Date.now() - 10 * 24 * 3600 * 1000).toISOString(),
      publishedAtPrecision: "EXACT_TIMESTAMP",
      collectedAt: new Date().toISOString(),
      language: "en",
      sanitizedExcerpt:
        "I would immediately swipe our corporate card for $250/mo if this saved our 6 engineers from spending the last week of every quarter gathering evidence.",
      problemSummary: "Explicit budget commitment of $250/mo for automated evidence",
      actorRole: "Startup CTO",
      workflowContext: "Budget allocation",
      purchaseIntent: true,
      spendingSignal: "$250/month credit card purchase",
      evidenceQuality: 0.96,
      recencyScore: 1.0,
      credibilityScore: 0.85,
      independenceKey: "hn:story:38501199",
      independenceMethod: "ROOT_THREAD",
      independenceConfidence: 1.0,
      verificationStatus: "VERIFIED",
      verificationMethod: "TRUSTED_API",
      verifiedAt: new Date(Date.now() - 9 * 24 * 3600 * 1000).toISOString(),
      verifiedBy: "HN Algolia Ingestion Bot",
      verificationNotes: "Verified exact quote match from public item.",
      lastAccessibilityCheckAt: new Date().toISOString(),
    },
  },
  {
    id: "link-v5",
    opportunityRevisionId: "rev-dev-1",
    normalizedSignalId: "sig-v5",
    claimType: "TECHNICAL_FEASIBILITY",
    claimIdentifier: "technical_feasibility",
    claimSnippet:
      "GitHub Actions OpenID Connect (OIDC) tokens and webhook signatures enable tamper-proof commit binding.",
    relationshipType: "SUPPORTS",
    supportStrength: "STRONG",
    relevanceScore: 0.9,
    explanation: "First-party documentation confirming native API technical feasibility.",
    signal: {
      id: "sig-v5",
      sourceName: "GitHub Docs",
      sourceType: "GITHUB_REST",
      sourceFamily: "CODE_HOST",
      credibilityTier: "TIER_1_PRIMARY",
      signalType: "TECHNOLOGY_ENABLER",
      evidenceOrigin: "COLLECTED",
      canonicalUrl:
        "https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect",
      originalUrl:
        "https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect",
      sourceTitle: "About security hardening with OpenID Connect",
      authorOrg: "GitHub Security Engineering",
      publishedAt: new Date(Date.now() - 60 * 24 * 3600 * 1000).toISOString(),
      publishedAtPrecision: "DAY",
      collectedAt: new Date().toISOString(),
      language: "en",
      sanitizedExcerpt:
        "OpenID Connect allows your GitHub Actions workflows to authenticate with cloud providers without storing long-lived secrets. Each workflow run receives a short-lived OIDC token containing signed claims about the commit and branch.",
      problemSummary: "OIDC signed claims provide native tamper-proof commit telemetry",
      actorRole: "Platform Architect",
      workflowContext: "Architecture validation",
      purchaseIntent: false,
      evidenceQuality: 1.0,
      recencyScore: 0.9,
      credibilityScore: 1.0,
      independenceKey: "github:docs:oidc",
      independenceMethod: "CANONICAL_DOC",
      independenceConfidence: 1.0,
      verificationStatus: "VERIFIED",
      verificationMethod: "TRUSTED_API",
      verifiedAt: new Date(Date.now() - 59 * 24 * 3600 * 1000).toISOString(),
      verifiedBy: "Docs Ingestion Spider",
      verificationNotes: "First party technical documentation.",
      lastAccessibilityCheckAt: new Date().toISOString(),
    },
  },
  {
    id: "link-v6",
    opportunityRevisionId: "rev-dev-1",
    normalizedSignalId: "sig-v6",
    claimType: "WILLINGNESS_TO_PAY",
    claimIdentifier: "willingness_to_pay",
    claimSnippet:
      "Some bootstrap teams maintain free in-house shell scripts and resist paying for commercial licenses.",
    relationshipType: "CONTRADICTS",
    supportStrength: "MODERATE",
    relevanceScore: 0.85,
    explanation: "Contradicting signal from solo bootstrap founder who uses free bash scripts.",
    signal: {
      id: "sig-v6",
      sourceName: "Reddit r/startups",
      sourceType: "REDDIT_OAUTH",
      sourceFamily: "COMMUNITY",
      credibilityTier: "TIER_2_CREDIBLE_PUBLIC",
      signalType: "CONTRADICTING_EVIDENCE",
      evidenceOrigin: "COLLECTED",
      canonicalUrl: "https://www.reddit.com/r/startups/comments/192m7a/diy_soc2_scripts/",
      originalUrl: "https://www.reddit.com/r/startups/comments/192m7a/diy_soc2_scripts/",
      sourceTitle: "We passed SOC2 with 3 simple bash scripts. Do not buy compliance tools.",
      authorOrg: "Solo Bootstrapper",
      publishedAt: new Date(Date.now() - 20 * 24 * 3600 * 1000).toISOString(),
      publishedAtPrecision: "DAY",
      collectedAt: new Date().toISOString(),
      language: "en",
      sanitizedExcerpt:
        "If you are under 10 people, just write a 50-line bash script that dumps git logs to an S3 bucket with Object Lock. Buying SaaS for this is a complete waste of runway.",
      problemSummary: "Sub-10 person teams can pass audits with free scripts",
      actorRole: "Solo Founder",
      workflowContext: "Bootstrapped cost minimization",
      purchaseIntent: false,
      evidenceQuality: 0.88,
      recencyScore: 0.95,
      credibilityScore: 0.75,
      independenceKey: "reddit:post:startups:192m7a",
      independenceMethod: "SUBMISSION_THREAD",
      independenceConfidence: 1.0,
      verificationStatus: "VERIFIED",
      verificationMethod: "TRUSTED_API",
      verifiedAt: new Date(Date.now() - 19 * 24 * 3600 * 1000).toISOString(),
      verifiedBy: "Reddit Community Crawler",
      verificationNotes: "Authentic contradictory post from practitioner.",
      lastAccessibilityCheckAt: new Date().toISOString(),
    },
  },
];
